package com.master.business.controller.user;

import com.master.business.domain.model.user.RolePower;
import com.master.business.service.user.IRolePowerService;
import com.master.core.annotation.SessionParam;
import com.master.core.framework.db.PagerBean;
import com.master.core.framework.web.AuthUser;
import com.master.core.framework.web.BaseController;
import com.master.core.framework.web.ResultData;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
  * t_role_power 角色权限控制器
  * @version v1.0.0
  * @since jdk1.8+
  * @author 123
  */
@Controller
@RequestMapping("/rolepower")
public class RolePowerController extends BaseController {
	private Logger log = LoggerFactory.getLogger(RolePowerController.class);

	@Autowired
	private IRolePowerService rolepowerService;	
	
	/**
	 * 获取
	 * @param id 
     * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/get", method={ RequestMethod.GET, RequestMethod.POST })
	public void get(@SessionParam("authuser") AuthUser authuser, String id, Model model){
		log.debug("###开始查询， id=[{}].", id);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = rolepowerService.get(id, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
	
	/**
	 * 查询
	 * @param rolepower 对象
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/find", method={ RequestMethod.POST })
	public void find(@SessionParam("authuser") AuthUser authuser, RolePower rolepower, Model model){
		log.debug("###开始根据条件{}查询", rolepower);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = rolepowerService.find(rolepower, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
	
	
	/**
	 * 分页查询
	 * @param authuser 操作用户信息
	 * @param page 分页参数
	 * @param model
	 */
	@RequestMapping(value="/find-by-page", method={ RequestMethod.POST })
	public void findPager(@SessionParam("authuser") AuthUser authuser,  RolePower rolepower,PagerBean page,Model model){
		log.debug("###开始根据条件{}分页查询", rolepower);
		ResultData resData = ResultData.init();
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			resData = rolepowerService.findPager(rolepower,page,authuser);
			collect(resData, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
	
	/**
	 * 添加
	 * @param rolepower 对象
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/add", method={ RequestMethod.POST })
	public void add(@SessionParam("authuser") AuthUser authuser, RolePower rolepower, Model model){
		log.debug("###开始查找添加， [{}]", rolepower);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = rolepowerService.add(rolepower, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
	
	/**
	 * 更新
	 * @param rolepower 对象
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/update", method={ RequestMethod.POST })
	public void update(@SessionParam("authuser") AuthUser authuser, RolePower rolepower, Model model){
		log.debug("###开始修改， [{}]", rolepower);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = rolepowerService.update(rolepower, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
	
	/**
	 * 删除
	 * @param id 
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/delete", method={ RequestMethod.POST })
	public void delete(@SessionParam("authuser") AuthUser authuser, String id,  Model model){
		log.debug("###开始删除对象，id={}.", id);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = rolepowerService.delete(id, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
}