package com.master.business.controller.user;


import com.master.business.domain.model.user.Role;
import com.master.business.service.user.IRoleService;
import com.master.core.annotation.SessionParam;
import com.master.core.framework.db.PagerBean;
import com.master.core.framework.web.AuthUser;
import com.master.core.framework.web.BaseController;
import com.master.core.framework.web.ResultData;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;



  
/**
  * t_role 角色控制器
  * @version v1.0.0
  * @since jdk1.8+
  * @author 123
  */
@Controller
@RequestMapping("/role")
public class RoleController extends BaseController {
	private Logger log = LoggerFactory.getLogger(RoleController.class);

	@Autowired
	private IRoleService roleService;	
	
	/**
	 * 获取
	 * @param roleid 
     * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/get", method={ RequestMethod.GET, RequestMethod.POST })
	public void get(@SessionParam("authuser") AuthUser authuser, String roleid, Model model){
		log.debug("###开始查询， roleid=[{}].", roleid);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = roleService.get(roleid, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
	
	/**
	 * 查询
	 * @param role 对象
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/find", method={ RequestMethod.POST })
	public void find(@SessionParam("authuser") AuthUser authuser, Role role, Model model){
		log.debug("###开始根据条件{}查询", role);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = roleService.find(role, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
	
	
	/**
	 * 分页查询
	 * @param authuser 操作用户信息
	 * @param page 分页参数
	 * @param model
	 */
	@RequestMapping(value="/find-by-page", method={ RequestMethod.POST })
	public void findPager(@SessionParam("authuser") AuthUser authuser,  Role role,PagerBean page,Model model){
		log.debug("###开始根据条件{}分页查询", role);
		ResultData resData = ResultData.init();
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			resData = roleService.findPager(role,page,authuser);
			collect(resData, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
	
	/**
	 * 添加
	 * @param role 对象
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/add", method={ RequestMethod.POST })
	public void add(@SessionParam("authuser") AuthUser authuser, Role role, Model model){
		log.debug("###开始查找添加， [{}]", role);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = roleService.add(role, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
	
	/**
	 * 更新
	 * @param role 对象
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/update", method={ RequestMethod.POST })
	public void update(@SessionParam("authuser") AuthUser authuser, Role role, Model model){
		log.debug("###开始修改， [{}]", role);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = roleService.update(role, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
	
	/**
	 * 删除
	 * @param roleid 
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/delete", method={ RequestMethod.POST })
	public void delete(@SessionParam("authuser") AuthUser authuser, String roleid,  Model model){
		log.debug("###开始删除对象，roleid={}.", roleid);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = roleService.delete(roleid, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}


	/**
	 * 角色列表
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/listRole", method={ RequestMethod.POST })
	public void listRole(@SessionParam("authuser") AuthUser authuser, Model model){
		log.debug("###开始查询角色列表， [{}]", authuser);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = roleService.listRole(authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}

	/**
	 * 添加
	 * @param role 对象
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/addRole", method={ RequestMethod.POST })
	public void addRole(@SessionParam("authuser") AuthUser authuser, Role role, Model model){
		log.debug("###开始添加role， [{}]", role);
		try {
//			These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = roleService.addRole(role, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}


	/**
	 * 删除
	 * @param roleid
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/removeRole", method={ RequestMethod.POST })
	public void removeRole(@SessionParam("authuser") AuthUser authuser, String roleid,  Model model){
		log.debug("###开始删除对象，roleid={}.", roleid);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = roleService.removeRole(roleid, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}

	/**
	 * 更新
	 * @param role 对象
	 * @param authuser 操作用户信息
	 * @param model
	 */
	@RequestMapping(value="/updateRole", method={ RequestMethod.POST })
	public void updateRole(@SessionParam("authuser") AuthUser authuser, Role role, Model model){
		log.debug("###开始修改， [{}]", role);
		try {
			//These code is generated by machine, if you want to modify the code, suggest you to remove this line
			ResultData data = roleService.updateRole(role, authuser);
			collect(data, model);
		} catch (Exception e) {
			collect(e, model);
		}
	}
}