package com.master.business.controller.user;


import com.master.business.domain.model.user.User;
import com.master.business.service.user.IUserService;
import com.master.core.annotation.SessionParam;
import com.master.core.framework.db.PagerBean;
import com.master.core.framework.web.AuthUser;
import com.master.core.framework.web.BaseController;
import com.master.core.framework.web.ResultData;
import org.apache.shiro.authz.annotation.RequiresAuthentication;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


/**
 * t_user 用户控制器
 *
 * @author 123
 * @version v1.0.0
 * @since jdk1.8+
 */

@Controller
@RequestMapping("/user")
public class UserController extends BaseController {
    private Logger log = LoggerFactory.getLogger(UserController.class);

    @Autowired
    private IUserService userService;

    /**
     * 获取
     *
     * @param userid
     * @param authuser 操作用户信息
     * @param model
     */
    @RequiresPermissions("user:list")
    @RequestMapping(value = "/get", method = {RequestMethod.GET, RequestMethod.POST})
    public void get(@SessionParam("authuser") AuthUser authuser, String userid, Model model) {
        log.debug("###开始查询， userid=[{}].", userid);
        try {
            //These code is generated by machine, if you want to modify the code, suggest you to remove this line
            ResultData data = userService.get(userid, authuser);
            collect(data, model);
        } catch (Exception e) {
            collect(e, model);
        }
    }

    /**
     * 查询
     *
     * @param user     对象
     * @param authuser 操作用户信息
     * @param model
     */
    @RequestMapping(value = "/find", method = {RequestMethod.POST})
    public void find(@SessionParam("authuser") AuthUser authuser, User user, Model model) {
        log.debug("###开始根据条件{}查询", user);
        try {
            //These code is generated by machine, if you want to modify the code, suggest you to remove this line
            ResultData data = userService.find(user, authuser);
            collect(data, model);
        } catch (Exception e) {
            collect(e, model);
        }
    }


    /**
     * 分页查询
     *
     * @param authuser 操作用户信息
     * @param page     分页参数
     * @param model
     */
    @RequestMapping(value = "/find-by-page", method = {RequestMethod.POST})
    public void findPager(@SessionParam("authuser") AuthUser authuser, User user, PagerBean page, Model model) {
        log.debug("###开始根据条件{}分页查询", user);
        ResultData resData = ResultData.init();
        try {
            //These code is generated by machine, if you want to modify the code, suggest you to remove this line
            resData = userService.findPager(user, page, authuser);
            collect(resData, model);
        } catch (Exception e) {
            collect(e, model);
        }
    }

    /**
     * 添加
     *
     * @param user     对象
     * @param authuser 操作用户信息
     * @param model
     */
    @RequestMapping(value = "/add", method = {RequestMethod.POST})
    public void add(@SessionParam("authuser") AuthUser authuser, User user, Model model) {
        log.debug("###开始查找添加， [{}]", user);
        try {
            //These code is generated by machine, if you want to modify the code, suggest you to remove this line
            ResultData data = userService.add(user, authuser);
            collect(data, model);
        } catch (Exception e) {
            collect(e, model);
        }
    }

    /**
     * 更新
     *
     * @param user     对象
     * @param authuser 操作用户信息
     * @param model
     */
    @RequestMapping(value = "/update", method = {RequestMethod.POST})
    public void update(@SessionParam("authuser") AuthUser authuser, User user, Model model) {
        log.debug("###开始修改， [{}]", user);
        try {
            //These code is generated by machine, if you want to modify the code, suggest you to remove this line
            ResultData data = userService.update(user, authuser);
            collect(data, model);
        } catch (Exception e) {
            collect(e, model);
        }
    }

    /**
     * 删除
     *
     * @param userid
     * @param authuser 操作用户信息
     * @param model
     */
    @RequestMapping(value = "/delete", method = {RequestMethod.POST})
    public void delete(@SessionParam("authuser") AuthUser authuser, String userid, Model model) {
        log.debug("###开始删除对象，userid={}.", userid);
        try {
            //These code is generated by machine, if you want to modify the code, suggest you to remove this line
            ResultData data = userService.delete(userid, authuser);
            collect(data, model);
        } catch (Exception e) {
            collect(e, model);
        }
    }

    /**
     * 获取用户的权限信息
     *
     * @param authuser 操作用户信息
     * @param model
     */
    @RequestMapping(value = "/info", method = {RequestMethod.POST})
    public void userInfo(@SessionParam("authuser") AuthUser authuser,  Model model) {
        log.debug("###开始查询用户权限，authuser={}.", authuser.getUserid());
        try {
            //These code is generated by machine, if you want to modify the code, suggest you to remove this line
            ResultData data = userService.powerInfo(authuser);
            collect(data, model);
        } catch (Exception e) {
            collect(e, model);
        }
    }

}