package com.master.business.service.user.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.master.core.framework.web.BaseService;
import com.master.core.framework.db.PagerBean;
import com.master.core.framework.db.QueryBean;
import com.master.core.framework.web.AuthUser;
import com.master.core.framework.web.ResultData;

import com.master.business.service.user.IPowerService;
import com.master.business.domain.iface.user.IPowerDao;
import com.master.business.domain.model.user.Power;


/**
 * IPowerService 权限 服务接口实现
 *
 * @author 123
 * @version v1.0.0
 * @since jdk1.8+
 */
@Service
public class PowerServiceImpl extends BaseService implements IPowerService {
    private Logger log = LoggerFactory.getLogger(PowerServiceImpl.class);

    @Autowired
    private IPowerDao powerDao;

    @Override
    public ResultData get(String powerid, AuthUser authuser) throws Exception {
        log.debug("###[服务] 开始查询权限 powerid=[{}]. ", powerid);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        Power power = powerDao.get(powerid);
        resData.setData("power", power);
        log.info("###[服务] 完成查询权限 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData find(Power power, AuthUser authuser) throws Exception {
        log.debug("###[服务] 开始根据条件{}查询权限", power);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        List<Power> powers = powerDao.find(power);
        resData.setData("powers", powers);
        log.info("###[服务] 完成查询权限 ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData findPager(Power power, PagerBean page, AuthUser authuser) throws Exception {
        log.debug("###[服务] 开始根据条件{}分页查询权限", power);
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();

        page = new PagerBean(page.getPageSize() == null ? 20 : page.getPageSize(), page.getCurrentPage());
        page.setOrderKey("intime");
        page.setAscend("desc");

        Map<String, Object> _data = new HashMap<String, Object>();

        QueryBean<Power> query = new QueryBean<Power>(page, power);
        List<Power> powers = powerDao.findByPage(query);

        _data.put("powers", getFieldValueList(powers));
        _data.put("page", page.parseMap());
        resData.setData(_data);

        log.info("###[服务] 完成分页查询权限 resData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData add(Power power, AuthUser authuser) throws Exception {
        log.debug("###[服务] 开始添加新权限, 操作用户:{}", authuser.getUsername());
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int inserted = powerDao.insert(power);
        resData.setData("inserted", inserted);
        log.info("###[服务] 完成添加新权限，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData update(Power power, AuthUser authuser) throws Exception {
        log.debug("###[服务] 开始修改权限, 操作用户:{}", authuser.getUsername());
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        int updated = powerDao.update(power);
        resData.setData("updated", updated);
        log.info("###[服务] 完成修改权限，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData delete(String powerid, AuthUser authuser) throws Exception {
        log.debug("###[服务] 开始删除权限, 操作用户:{}", authuser.getUsername());
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        Power power = new Power();
        power.setPowerid(powerid);
        int deleted = powerDao.delete(power);
        resData.setData("deleted", deleted);
        log.info("###[服务] 完成删除权限，ResultData=[{}]", resData);
        return resData;
    }

    @Override
    public ResultData listAllPermission(AuthUser authuser) throws Exception {
        log.debug("###[服务] 开始查询所有权限 ,操作用户:{}", authuser.getUsername());
        //These code is generated by machine, if you want to modify the code, suggest you to remove this line
        ResultData resData = ResultData.init();
        List<Power> list = powerDao.listAllPermission();
        resData.setData("powers", list);
        log.info("###[服务] 完成查询权限 ResultData=[{}]", resData);
        return resData;
    }

}
