package com.master.business.service.user.impl;

import com.master.business.domain.iface.user.IRoleDao;
import com.master.business.domain.model.user.Role;
import com.master.business.service.user.IRoleService;
import com.master.core.framework.db.PagerBean;
import com.master.core.framework.db.QueryBean;
import com.master.core.framework.web.AuthUser;
import com.master.core.framework.web.BaseService;
import com.master.core.framework.web.ResultData;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
  * IRoleService 服务接口实现
  * @version v1.0.0
  * @since jdk1.8+
  * @author 123
  */
@Service
public class RoleServiceImpl extends BaseService implements IRoleService{
	private Logger log = LoggerFactory.getLogger(RoleServiceImpl.class);
	
	@Autowired
	private IRoleDao roleDao;
	
	@Override
	public ResultData get(String roleid, AuthUser authuser) throws Exception {
		log.debug("###[服务] 开始查询 roleid=[{}]. ", roleid);
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		Role role = roleDao.get(roleid);
		resData.setData("role", role);
		log.info("###[服务] 完成查询 ResultData=[{}]", resData);
		return resData;
	}
	
	@Override
	public ResultData find(Role role, AuthUser authuser) throws Exception {
		log.debug("###[服务] 开始根据条件{}查询", role);
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		List<Role> roles = roleDao.find(role);
		resData.setData("roles", roles);
		log.info("###[服务] 完成查询 ResultData=[{}]", resData);
		return resData;
	}
	
	@Override
	public ResultData findPager(Role role,PagerBean page, AuthUser authuser) throws Exception{
		log.debug("###[服务] 开始根据条件{}分页查询", role);
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		
		page = new PagerBean(20, page.getCurrentPage());
		page.setOrderKey("intime");
		page.setAscend("desc");

		Map<String, Object> _data = new HashMap<String, Object>();
		
		QueryBean<Role> query = new QueryBean<Role>(page, role);
		List<Role> roles = roleDao.findByPage(query);
		
		_data.put("roles", getFieldValueList(roles));
		_data.put("page", page.parseMap());
		resData.setData(_data);
		
		log.info("###[服务] 完成分页查询 resData=[{}]", resData);
		return resData;
	}
	
	@Override
	public ResultData add(Role role, AuthUser authuser) throws Exception {
		log.debug("###[服务] 开始添加新, 操作用户:{}", authuser.getUsername());
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		int inserted = roleDao.insert(role);
		resData.setData("inserted", inserted);
		log.info("###[服务] 完成添加新，ResultData=[{}]", resData);
		return resData;
	}
	
	@Override
	public ResultData update(Role role, AuthUser authuser) throws Exception {
		log.debug("###[服务] 开始修改, 操作用户:{}", authuser.getUsername());
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		int updated = roleDao.update(role);
		resData.setData("updated", updated);
		log.info("###[服务] 完成修改，ResultData=[{}]", resData);
		return resData;
	}
	
	@Override
	public ResultData delete(String roleid, AuthUser authuser) throws Exception {
		log.debug("###[服务] 开始删除, 操作用户:{}", authuser.getUsername());
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		Role role = new Role();
		role.setRoleid(roleid);
		int deleted = roleDao.delete(role);
		resData.setData("deleted", deleted);
		log.info("###[服务] 完成删除，ResultData=[{}]", resData);
		return resData;
	}
}
