package com.master.business.service.user.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.master.core.framework.web.BaseService;
import com.master.core.framework.db.PagerBean;
import com.master.core.framework.db.QueryBean;
import com.master.core.framework.web.AuthUser;
import com.master.core.framework.web.ResultData;

import com.master.business.service.user.IRolePowerService;
import com.master.business.domain.iface.user.IRolePowerDao;
import com.master.business.domain.model.user.RolePower;

  
/**
  * IRolePowerService 服务接口实现
  * @version v1.0.0
  * @since jdk1.8+
  * @author 123
  */
@Service
public class RolePowerServiceImpl extends BaseService implements IRolePowerService{
	private Logger log = LoggerFactory.getLogger(RolePowerServiceImpl.class);
	
	@Autowired
	private IRolePowerDao rolepowerDao;
	
	@Override
	public ResultData get(String id, AuthUser authuser) throws Exception {
		log.debug("###[服务] 开始查询 id=[{}]. ", id);
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		RolePower rolepower = rolepowerDao.get(id);
		resData.setData("rolepower", rolepower);
		log.info("###[服务] 完成查询 ResultData=[{}]", resData);
		return resData;
	}
	
	@Override
	public ResultData find(RolePower rolepower, AuthUser authuser) throws Exception {
		log.debug("###[服务] 开始根据条件{}查询", rolepower);
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		List<RolePower> rolepowers = rolepowerDao.find(rolepower);
		resData.setData("rolepowers", rolepowers);
		log.info("###[服务] 完成查询 ResultData=[{}]", resData);
		return resData;
	}
	
	@Override
	public ResultData findPager(RolePower rolepower,PagerBean page, AuthUser authuser) throws Exception{
		log.debug("###[服务] 开始根据条件{}分页查询", rolepower);
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		
		page = new PagerBean(page.getPageSize() == null ? 20 : page.getPageSize(), page.getCurrentPage());
		page.setOrderKey("intime");
		page.setAscend("desc");

		Map<String, Object> _data = new HashMap<String, Object>();
		
		QueryBean<RolePower> query = new QueryBean<RolePower>(page, rolepower);
		List<RolePower> rolepowers = rolepowerDao.findByPage(query);
		
		_data.put("rolepowers", getFieldValueList(rolepowers));
		_data.put("page", page.parseMap());
		resData.setData(_data);
		
		log.info("###[服务] 完成分页查询 resData=[{}]", resData);
		return resData;
	}
	
	@Override
	public ResultData add(RolePower rolepower, AuthUser authuser) throws Exception {
		log.debug("###[服务] 开始添加新, 操作用户:{}", authuser.getUsername());
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		int inserted = rolepowerDao.insert(rolepower);
		resData.setData("inserted", inserted);
		log.info("###[服务] 完成添加新，ResultData=[{}]", resData);
		return resData;
	}
	
	@Override
	public ResultData update(RolePower rolepower, AuthUser authuser) throws Exception {
		log.debug("###[服务] 开始修改, 操作用户:{}", authuser.getUsername());
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		int updated = rolepowerDao.update(rolepower);
		resData.setData("updated", updated);
		log.info("###[服务] 完成修改，ResultData=[{}]", resData);
		return resData;
	}
	
	@Override
	public ResultData delete(String id, AuthUser authuser) throws Exception {
		log.debug("###[服务] 开始删除, 操作用户:{}", authuser.getUsername());
		//These code is generated by machine, if you want to modify the code, suggest you to remove this line
		ResultData resData = ResultData.init();
		RolePower rolepower = new RolePower();
		int deleted = rolepowerDao.delete(rolepower);
		resData.setData("deleted", deleted);
		log.info("###[服务] 完成删除，ResultData=[{}]", resData);
		return resData;
	}
}
